const types={
  SHOW_LOADING:'SHOW_LOADING',
  HIDE_LOADING:'HIDE_LOADING',
  SHOW_POP:'SHOW_POP',
  HIDE_POP:'HIDE_POP',
  UPDATE_LIST:'UPDATE_LIST',
  REMOVE_ITEM:'REMOVE_ITEM',
  ADD_ITEM:'ADD_ITEM',
  REMOVE_ALL:'REMOVE_ALL',

};
export default types;